
# Site settings
title: Dayman Novaes
email: daymannovaes@gmai.com
description: > # this means to ignore newlines until "baseurl:"
  Um blog sobre desenvolvimento e conhecimento
baseurl: "/blog"
url: "http://me.dayman.io"

twitter_username: daymannovaes
facebook_username: daymannovaes
github_username:  daymannovaes

# Build settings
highlighter: pygments
markdown: kramdown
permalink: /post/:title/