
# Site settings
title: Dayman Novaes
email: daymannovaes@gmai.com
description: > # this means to ignore newlines until "baseurl:"
  Um pouco de filosofia sobre desenvolvimento, quer ouvir a minha opinião?
baseurl: "/blog"
url: "http://me.dayman.io"

twitter_username: daymannovaes
facebook_username: daymannovaes
github_username:  daymannovaes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/